/*
  # Durable contract generation jobs queue + provenance metadata

  Goals:
  - Persist contract generation failures from webhook flow for retry.
  - Provide a claimable queue for a dedicated worker.
  - Track provenance when contracts are generated by fallback paths.
*/

BEGIN;

-- 1) Purchases provenance metadata (nullable, backward compatible).
ALTER TABLE public.purchases
  ADD COLUMN IF NOT EXISTS contract_generated_by text,
  ADD COLUMN IF NOT EXISTS contract_generated_at timestamptz;

ALTER TABLE public.purchases
  DROP CONSTRAINT IF EXISTS purchases_contract_generated_by_check;

ALTER TABLE public.purchases
  ADD CONSTRAINT purchases_contract_generated_by_check
  CHECK (
    contract_generated_by IS NULL
    OR contract_generated_by IN ('api', 'edge_fallback', 'contract_worker')
  );

-- 2) Durable queue table for contract generation retries.
CREATE TABLE IF NOT EXISTS public.contract_generation_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  purchase_id uuid NOT NULL REFERENCES public.purchases(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'pending',
  attempts integer NOT NULL DEFAULT 0,
  last_error text,
  next_run_at timestamptz NOT NULL DEFAULT now(),
  locked_at timestamptz,
  locked_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT contract_generation_jobs_status_check CHECK (status IN ('pending', 'processing', 'succeeded', 'failed')),
  CONSTRAINT contract_generation_jobs_attempts_check CHECK (attempts >= 0)
);

CREATE INDEX IF NOT EXISTS idx_contract_generation_jobs_status_next_run_at
  ON public.contract_generation_jobs (status, next_run_at, created_at);

CREATE INDEX IF NOT EXISTS idx_contract_generation_jobs_purchase_created_at
  ON public.contract_generation_jobs (purchase_id, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_contract_generation_jobs_active_purchase
  ON public.contract_generation_jobs (purchase_id)
  WHERE status IN ('pending', 'processing');

ALTER TABLE public.contract_generation_jobs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can read contract generation jobs" ON public.contract_generation_jobs;
CREATE POLICY "Admins can read contract generation jobs"
  ON public.contract_generation_jobs
  FOR SELECT
  TO authenticated
  USING (public.is_admin(auth.uid()));

REVOKE ALL ON TABLE public.contract_generation_jobs FROM PUBLIC;
REVOKE ALL ON TABLE public.contract_generation_jobs FROM anon;
REVOKE ALL ON TABLE public.contract_generation_jobs FROM authenticated;
GRANT SELECT ON TABLE public.contract_generation_jobs TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.contract_generation_jobs TO service_role;

DO $$
BEGIN
  IF to_regproc('public.update_updated_at_column()') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_trigger
       WHERE tgname = 'update_contract_generation_jobs_updated_at'
         AND tgrelid = 'public.contract_generation_jobs'::regclass
         AND NOT tgisinternal
     ) THEN
    DROP TRIGGER IF EXISTS update_contract_generation_jobs_updated_at ON public.contract_generation_jobs;
    CREATE TRIGGER update_contract_generation_jobs_updated_at
      BEFORE UPDATE ON public.contract_generation_jobs
      FOR EACH ROW
      EXECUTE FUNCTION public.update_updated_at_column();
  END IF;
END
$$;

-- 3) Enqueue helper used by webhook and workers.
CREATE OR REPLACE FUNCTION public.enqueue_contract_generation_job(
  p_purchase_id uuid
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_actor uuid := auth.uid();
  v_jwt_role text := COALESCE(auth.jwt()->>'role', '');
  v_existing_id uuid;
  v_inserted_id uuid;
BEGIN
  IF p_purchase_id IS NULL THEN
    RAISE EXCEPTION 'purchase_required';
  END IF;

  IF NOT (v_jwt_role = 'service_role' OR public.is_admin(v_actor)) THEN
    RAISE EXCEPTION 'admin_or_service_role_required';
  END IF;

  SELECT id
  INTO v_existing_id
  FROM public.contract_generation_jobs
  WHERE purchase_id = p_purchase_id
    AND status IN ('pending', 'processing')
  ORDER BY created_at DESC
  LIMIT 1;

  IF v_existing_id IS NOT NULL THEN
    RETURN v_existing_id;
  END IF;

  BEGIN
    INSERT INTO public.contract_generation_jobs (
      purchase_id,
      status,
      attempts,
      last_error,
      next_run_at,
      locked_at,
      locked_by
    )
    VALUES (
      p_purchase_id,
      'pending',
      0,
      NULL,
      now(),
      NULL,
      NULL
    )
    RETURNING id INTO v_inserted_id;
  EXCEPTION
    WHEN unique_violation THEN
      SELECT id
      INTO v_inserted_id
      FROM public.contract_generation_jobs
      WHERE purchase_id = p_purchase_id
        AND status IN ('pending', 'processing')
      ORDER BY created_at DESC
      LIMIT 1;
  END;

  RETURN v_inserted_id;
END;
$$;

-- 4) Claim helper for the contract worker.
CREATE OR REPLACE FUNCTION public.claim_contract_generation_jobs(
  p_limit integer DEFAULT 10,
  p_worker text DEFAULT NULL
)
RETURNS SETOF public.contract_generation_jobs
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_actor uuid := auth.uid();
  v_jwt_role text := COALESCE(auth.jwt()->>'role', '');
  v_limit integer := LEAST(GREATEST(COALESCE(p_limit, 10), 1), 100);
  v_worker text := COALESCE(NULLIF(btrim(COALESCE(p_worker, '')), ''), 'contract-worker');
BEGIN
  IF NOT (v_jwt_role = 'service_role' OR public.is_admin(v_actor)) THEN
    RAISE EXCEPTION 'admin_or_service_role_required';
  END IF;

  RETURN QUERY
  WITH reclaimed AS (
    UPDATE public.contract_generation_jobs j
    SET
      status = 'failed',
      last_error = COALESCE(j.last_error, 'stale_processing_lock'),
      locked_at = NULL,
      locked_by = NULL,
      next_run_at = now(),
      updated_at = now()
    WHERE j.status = 'processing'
      AND j.locked_at IS NOT NULL
      AND j.locked_at < now() - interval '10 minutes'
    RETURNING j.id
  ),
  candidates AS (
    SELECT j.id
    FROM public.contract_generation_jobs j
    WHERE j.status IN ('pending', 'failed')
      AND j.next_run_at <= now()
    ORDER BY j.next_run_at ASC, j.created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT v_limit
  ),
  claimed AS (
    UPDATE public.contract_generation_jobs j
    SET
      status = 'processing',
      attempts = j.attempts + 1,
      locked_at = now(),
      locked_by = v_worker,
      updated_at = now()
    FROM candidates c
    WHERE j.id = c.id
    RETURNING j.*
  )
  SELECT * FROM claimed;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.enqueue_contract_generation_job(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.enqueue_contract_generation_job(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.enqueue_contract_generation_job(uuid) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.enqueue_contract_generation_job(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.enqueue_contract_generation_job(uuid) TO authenticated;

REVOKE EXECUTE ON FUNCTION public.claim_contract_generation_jobs(integer, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.claim_contract_generation_jobs(integer, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.claim_contract_generation_jobs(integer, text) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.claim_contract_generation_jobs(integer, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.claim_contract_generation_jobs(integer, text) TO authenticated;

COMMIT;
